namespace POS.Item
{
    partial class SupplierMaster
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SupplierMaster));
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            this.lbluser = new Infragistics.Win.Misc.UltraLabel();
            this.lblname = new Infragistics.Win.Misc.UltraLabel();
            this.lblcode = new Infragistics.Win.Misc.UltraLabel();
            this.lbltitle = new System.Windows.Forms.Label();
            this.panel1 = new System.Windows.Forms.Panel();
            this.panel2 = new System.Windows.Forms.Panel();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.btnClose = new Bunifu.Framework.UI.BunifuImageButton();
            this.btnDelete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtusername = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtname = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtcode = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.chkblock = new Bunifu.Framework.UI.BunifuCheckbox();
            this.lblstatus = new Infragistics.Win.Misc.UltraLabel();
            this.txtaddress1 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lbladdress1 = new Infragistics.Win.Misc.UltraLabel();
            this.lbladdress2 = new Infragistics.Win.Misc.UltraLabel();
            this.txtaddress2 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblphone1 = new Infragistics.Win.Misc.UltraLabel();
            this.txtphone1 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblemail = new Infragistics.Win.Misc.UltraLabel();
            this.txtemail = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblwebsite = new Infragistics.Win.Misc.UltraLabel();
            this.txtwebsite = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lbllicence = new Infragistics.Win.Misc.UltraLabel();
            this.txtlicence = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblremarks = new Infragistics.Win.Misc.UltraLabel();
            this.txtremark = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblphone2 = new Infragistics.Win.Misc.UltraLabel();
            this.txtphon2 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtfax = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblfax = new Infragistics.Win.Misc.UltraLabel();
            ((System.ComponentModel.ISupportInitialize)(this.btnClose)).BeginInit();
            this.SuspendLayout();
            // 
            // lbluser
            // 
            appearance1.ForeColor = System.Drawing.Color.White;
            this.lbluser.Appearance = appearance1;
            this.lbluser.Font = new System.Drawing.Font("Arial", 8.25F, System.Drawing.FontStyle.Bold);
            this.lbluser.Location = new System.Drawing.Point(287, 74);
            this.lbluser.Name = "lbluser";
            this.lbluser.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.lbluser.Size = new System.Drawing.Size(99, 16);
            this.lbluser.TabIndex = 84;
            this.lbluser.Text = ": User";
            // 
            // lblname
            // 
            appearance2.BorderColor = System.Drawing.Color.White;
            appearance2.ForeColor = System.Drawing.Color.White;
            this.lblname.Appearance = appearance2;
            this.lblname.Font = new System.Drawing.Font("Arial", 8.25F, System.Drawing.FontStyle.Bold);
            this.lblname.Location = new System.Drawing.Point(60, 105);
            this.lblname.Name = "lblname";
            this.lblname.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.lblname.Size = new System.Drawing.Size(45, 19);
            this.lblname.TabIndex = 77;
            this.lblname.Text = ": Name";
            // 
            // lblcode
            // 
            appearance3.ForeColor = System.Drawing.Color.White;
            this.lblcode.Appearance = appearance3;
            this.lblcode.Font = new System.Drawing.Font("Arial", 8.25F, System.Drawing.FontStyle.Bold);
            this.lblcode.Location = new System.Drawing.Point(12, 72);
            this.lblcode.Name = "lblcode";
            this.lblcode.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.lblcode.Size = new System.Drawing.Size(93, 23);
            this.lblcode.TabIndex = 75;
            this.lblcode.Text = ": Code";
            // 
            // lbltitle
            // 
            this.lbltitle.AutoSize = true;
            this.lbltitle.Font = new System.Drawing.Font("Arial", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbltitle.ForeColor = System.Drawing.Color.White;
            this.lbltitle.Location = new System.Drawing.Point(223, 9);
            this.lbltitle.Name = "lbltitle";
            this.lbltitle.Size = new System.Drawing.Size(110, 29);
            this.lbltitle.TabIndex = 94;
            this.lbltitle.Text = "Supplier";
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.White;
            this.panel1.Location = new System.Drawing.Point(-1, 44);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(569, 2);
            this.panel1.TabIndex = 97;
            // 
            // panel2
            // 
            this.panel2.BackColor = System.Drawing.Color.White;
            this.panel2.Location = new System.Drawing.Point(2, 423);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(569, 2);
            this.panel2.TabIndex = 98;
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 25;
            this.bunifuElipse1.TargetControl = this;
            // 
            // btnClose
            // 
            this.btnClose.Image = global::POS.Properties.Resources.icons8_macos_close_28;
            this.btnClose.ImageActive = null;
            this.btnClose.Location = new System.Drawing.Point(528, 4);
            this.btnClose.Name = "btnClose";
            this.btnClose.Size = new System.Drawing.Size(22, 23);
            this.btnClose.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.btnClose.TabIndex = 113;
            this.btnClose.TabStop = false;
            this.btnClose.Zoom = 10;
            this.btnClose.Click += new System.EventHandler(this.BtnClose_Click);
            // 
            // btnDelete
            // 
            this.btnDelete.AllowToggling = true;
            this.btnDelete.AnimationSpeed = 200;
            this.btnDelete.AutoGenerateColors = false;
            this.btnDelete.BackColor = System.Drawing.Color.Transparent;
            this.btnDelete.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnDelete.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDelete.BackgroundImage")));
            this.btnDelete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.btnDelete.ButtonText = "Delete";
            this.btnDelete.ButtonTextMarginLeft = 18;
            this.btnDelete.ColorContrastOnClick = 45;
            this.btnDelete.ColorContrastOnHover = 45;
            this.btnDelete.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = false;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = false;
            borderEdges1.TopRight = true;
            this.btnDelete.CustomizableEdges = borderEdges1;
            this.btnDelete.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDelete.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnDelete.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDelete.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDelete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDelete.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnDelete.ForeColor = System.Drawing.Color.White;
            this.btnDelete.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnDelete.IconMarginLeft = 11;
            this.btnDelete.IconPadding = 5;
            this.btnDelete.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnDelete.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnDelete.IdleBorderRadius = 25;
            this.btnDelete.IdleBorderThickness = 2;
            this.btnDelete.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnDelete.IdleIconLeftImage = global::POS.Properties.Resources.icons8_delete_bin_28;
            this.btnDelete.IdleIconRightImage = null;
            this.btnDelete.IndicateFocus = true;
            this.btnDelete.Location = new System.Drawing.Point(274, 431);
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDelete.onHoverState.BorderRadius = 25;
            this.btnDelete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.onHoverState.BorderThickness = 2;
            this.btnDelete.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnDelete.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDelete.onHoverState.IconLeftImage = null;
            this.btnDelete.onHoverState.IconRightImage = null;
            this.btnDelete.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnDelete.OnIdleState.BorderRadius = 25;
            this.btnDelete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.btnDelete.OnIdleState.BorderThickness = 2;
            this.btnDelete.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnDelete.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDelete.OnIdleState.IconLeftImage = global::POS.Properties.Resources.icons8_delete_bin_28;
            this.btnDelete.OnIdleState.IconRightImage = null;
            this.btnDelete.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDelete.OnPressedState.BorderRadius = 25;
            this.btnDelete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.OnPressedState.BorderThickness = 2;
            this.btnDelete.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDelete.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDelete.OnPressedState.IconLeftImage = null;
            this.btnDelete.OnPressedState.IconRightImage = null;
            this.btnDelete.Size = new System.Drawing.Size(111, 37);
            this.btnDelete.TabIndex = 112;
            this.btnDelete.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDelete.TextMarginLeft = 18;
            this.btnDelete.UseDefaultRadiusAndThickness = true;
            this.btnDelete.Click += new System.EventHandler(this.BtnDelete_Click);
            // 
            // btnSave
            // 
            this.btnSave.AllowToggling = true;
            this.btnSave.AnimationSpeed = 200;
            this.btnSave.AutoGenerateColors = false;
            this.btnSave.BackColor = System.Drawing.Color.Transparent;
            this.btnSave.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnSave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSave.BackgroundImage")));
            this.btnSave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.btnSave.ButtonText = "Save";
            this.btnSave.ButtonTextMarginLeft = 18;
            this.btnSave.ColorContrastOnClick = 45;
            this.btnSave.ColorContrastOnHover = 45;
            this.btnSave.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = false;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = false;
            this.btnSave.CustomizableEdges = borderEdges2;
            this.btnSave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSave.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnSave.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSave.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSave.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnSave.ForeColor = System.Drawing.Color.White;
            this.btnSave.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSave.IconMarginLeft = 11;
            this.btnSave.IconPadding = 5;
            this.btnSave.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSave.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSave.IdleBorderRadius = 25;
            this.btnSave.IdleBorderThickness = 2;
            this.btnSave.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnSave.IdleIconLeftImage = global::POS.Properties.Resources.icons8_save_28;
            this.btnSave.IdleIconRightImage = null;
            this.btnSave.IndicateFocus = true;
            this.btnSave.Location = new System.Drawing.Point(163, 431);
            this.btnSave.Name = "btnSave";
            this.btnSave.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSave.onHoverState.BorderRadius = 25;
            this.btnSave.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.onHoverState.BorderThickness = 2;
            this.btnSave.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSave.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSave.onHoverState.IconLeftImage = null;
            this.btnSave.onHoverState.IconRightImage = null;
            this.btnSave.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSave.OnIdleState.BorderRadius = 25;
            this.btnSave.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.btnSave.OnIdleState.BorderThickness = 2;
            this.btnSave.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnSave.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnIdleState.IconLeftImage = global::POS.Properties.Resources.icons8_save_28;
            this.btnSave.OnIdleState.IconRightImage = null;
            this.btnSave.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSave.OnPressedState.BorderRadius = 25;
            this.btnSave.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnPressedState.BorderThickness = 2;
            this.btnSave.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSave.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnPressedState.IconLeftImage = null;
            this.btnSave.OnPressedState.IconRightImage = null;
            this.btnSave.Size = new System.Drawing.Size(111, 37);
            this.btnSave.TabIndex = 111;
            this.btnSave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSave.TextMarginLeft = 18;
            this.btnSave.UseDefaultRadiusAndThickness = true;
            this.btnSave.Click += new System.EventHandler(this.BtnSave_Click);
            // 
            // txtusername
            // 
            this.txtusername.AcceptsReturn = false;
            this.txtusername.AcceptsTab = false;
            this.txtusername.AnimationSpeed = 200;
            this.txtusername.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtusername.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtusername.BackColor = System.Drawing.Color.Transparent;
            this.txtusername.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtusername.BackgroundImage")));
            this.txtusername.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtusername.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtusername.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtusername.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtusername.BorderRadius = 15;
            this.txtusername.BorderThickness = 1;
            this.txtusername.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtusername.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtusername.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtusername.DefaultText = "";
            this.txtusername.FillColor = System.Drawing.Color.White;
            this.txtusername.ForeColor = System.Drawing.Color.Red;
            this.txtusername.HideSelection = true;
            this.txtusername.IconLeft = null;
            this.txtusername.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtusername.IconPadding = 10;
            this.txtusername.IconRight = null;
            this.txtusername.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtusername.Lines = new string[0];
            this.txtusername.Location = new System.Drawing.Point(389, 67);
            this.txtusername.MaxLength = 32767;
            this.txtusername.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtusername.Modified = false;
            this.txtusername.Multiline = false;
            this.txtusername.Name = "txtusername";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtusername.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.Empty;
            stateProperties38.FillColor = System.Drawing.Color.White;
            stateProperties38.ForeColor = System.Drawing.Color.Empty;
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtusername.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtusername.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Red;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtusername.OnIdleState = stateProperties40;
            this.txtusername.PasswordChar = '\0';
            this.txtusername.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtusername.PlaceholderText = "User Name";
            this.txtusername.ReadOnly = true;
            this.txtusername.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtusername.SelectedText = "";
            this.txtusername.SelectionLength = 0;
            this.txtusername.SelectionStart = 0;
            this.txtusername.ShortcutsEnabled = true;
            this.txtusername.Size = new System.Drawing.Size(113, 25);
            this.txtusername.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtusername.TabIndex = 103;
            this.txtusername.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtusername.TextMarginBottom = 0;
            this.txtusername.TextMarginLeft = 5;
            this.txtusername.TextMarginTop = 0;
            this.txtusername.TextPlaceholder = "User Name";
            this.txtusername.UseSystemPasswordChar = false;
            this.txtusername.WordWrap = true;
            // 
            // txtname
            // 
            this.txtname.AcceptsReturn = false;
            this.txtname.AcceptsTab = false;
            this.txtname.AnimationSpeed = 200;
            this.txtname.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtname.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtname.BackColor = System.Drawing.Color.Transparent;
            this.txtname.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtname.BackgroundImage")));
            this.txtname.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtname.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtname.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtname.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtname.BorderRadius = 10;
            this.txtname.BorderThickness = 1;
            this.txtname.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
            this.txtname.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtname.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtname.DefaultText = "";
            this.txtname.FillColor = System.Drawing.Color.White;
            this.txtname.HideSelection = true;
            this.txtname.IconLeft = null;
            this.txtname.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtname.IconPadding = 10;
            this.txtname.IconRight = null;
            this.txtname.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtname.Lines = new string[0];
            this.txtname.Location = new System.Drawing.Point(110, 102);
            this.txtname.MaxLength = 32767;
            this.txtname.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtname.Modified = false;
            this.txtname.Multiline = false;
            this.txtname.Name = "txtname";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtname.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.Empty;
            stateProperties42.FillColor = System.Drawing.Color.White;
            stateProperties42.ForeColor = System.Drawing.Color.Empty;
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtname.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtname.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtname.OnIdleState = stateProperties44;
            this.txtname.PasswordChar = '\0';
            this.txtname.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtname.PlaceholderText = "NAME";
            this.txtname.ReadOnly = false;
            this.txtname.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtname.SelectedText = "";
            this.txtname.SelectionLength = 0;
            this.txtname.SelectionStart = 0;
            this.txtname.ShortcutsEnabled = true;
            this.txtname.Size = new System.Drawing.Size(391, 25);
            this.txtname.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtname.TabIndex = 102;
            this.txtname.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtname.TextMarginBottom = 0;
            this.txtname.TextMarginLeft = 5;
            this.txtname.TextMarginTop = 0;
            this.txtname.TextPlaceholder = "NAME";
            this.txtname.UseSystemPasswordChar = false;
            this.txtname.WordWrap = true;
            this.txtname.KeyDown += new System.Windows.Forms.KeyEventHandler(this.Txtname_KeyDown);
            // 
            // txtcode
            // 
            this.txtcode.AcceptsReturn = false;
            this.txtcode.AcceptsTab = false;
            this.txtcode.AnimationSpeed = 200;
            this.txtcode.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtcode.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtcode.BackColor = System.Drawing.Color.Transparent;
            this.txtcode.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtcode.BackgroundImage")));
            this.txtcode.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtcode.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtcode.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtcode.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtcode.BorderRadius = 15;
            this.txtcode.BorderThickness = 1;
            this.txtcode.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtcode.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtcode.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtcode.DefaultText = "";
            this.txtcode.FillColor = System.Drawing.Color.White;
            this.txtcode.HideSelection = true;
            this.txtcode.IconLeft = null;
            this.txtcode.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtcode.IconPadding = 10;
            this.txtcode.IconRight = null;
            this.txtcode.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtcode.Lines = new string[0];
            this.txtcode.Location = new System.Drawing.Point(110, 67);
            this.txtcode.MaxLength = 32767;
            this.txtcode.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtcode.Modified = false;
            this.txtcode.Multiline = false;
            this.txtcode.Name = "txtcode";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtcode.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.Empty;
            stateProperties46.FillColor = System.Drawing.Color.White;
            stateProperties46.ForeColor = System.Drawing.Color.Empty;
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtcode.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtcode.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtcode.OnIdleState = stateProperties48;
            this.txtcode.PasswordChar = '\0';
            this.txtcode.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtcode.PlaceholderText = "Code";
            this.txtcode.ReadOnly = true;
            this.txtcode.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtcode.SelectedText = "";
            this.txtcode.SelectionLength = 0;
            this.txtcode.SelectionStart = 0;
            this.txtcode.ShortcutsEnabled = true;
            this.txtcode.Size = new System.Drawing.Size(100, 25);
            this.txtcode.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtcode.TabIndex = 101;
            this.txtcode.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtcode.TextMarginBottom = 0;
            this.txtcode.TextMarginLeft = 5;
            this.txtcode.TextMarginTop = 0;
            this.txtcode.TextPlaceholder = "Code";
            this.txtcode.UseSystemPasswordChar = false;
            this.txtcode.WordWrap = true;
            // 
            // chkblock
            // 
            this.chkblock.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(205)))), ((int)(((byte)(117)))));
            this.chkblock.ChechedOffColor = System.Drawing.Color.FromArgb(((int)(((byte)(132)))), ((int)(((byte)(135)))), ((int)(((byte)(140)))));
            this.chkblock.Checked = true;
            this.chkblock.CheckedOnColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(205)))), ((int)(((byte)(117)))));
            this.chkblock.ForeColor = System.Drawing.Color.White;
            this.chkblock.Location = new System.Drawing.Point(213, 70);
            this.chkblock.Name = "chkblock";
            this.chkblock.Size = new System.Drawing.Size(20, 20);
            this.chkblock.TabIndex = 114;
            // 
            // lblstatus
            // 
            appearance13.ForeColor = System.Drawing.Color.White;
            this.lblstatus.Appearance = appearance13;
            this.lblstatus.Font = new System.Drawing.Font("Arial", 8.25F, System.Drawing.FontStyle.Bold);
            this.lblstatus.Location = new System.Drawing.Point(233, 72);
            this.lblstatus.Name = "lblstatus";
            this.lblstatus.Size = new System.Drawing.Size(84, 20);
            this.lblstatus.TabIndex = 115;
            this.lblstatus.Text = "Active";
            // 
            // txtaddress1
            // 
            this.txtaddress1.AcceptsReturn = false;
            this.txtaddress1.AcceptsTab = false;
            this.txtaddress1.AnimationSpeed = 200;
            this.txtaddress1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtaddress1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtaddress1.BackColor = System.Drawing.Color.Transparent;
            this.txtaddress1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtaddress1.BackgroundImage")));
            this.txtaddress1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtaddress1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtaddress1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtaddress1.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtaddress1.BorderRadius = 10;
            this.txtaddress1.BorderThickness = 1;
            this.txtaddress1.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
            this.txtaddress1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtaddress1.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtaddress1.DefaultText = "";
            this.txtaddress1.FillColor = System.Drawing.Color.White;
            this.txtaddress1.HideSelection = true;
            this.txtaddress1.IconLeft = null;
            this.txtaddress1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtaddress1.IconPadding = 10;
            this.txtaddress1.IconRight = null;
            this.txtaddress1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtaddress1.Lines = new string[0];
            this.txtaddress1.Location = new System.Drawing.Point(110, 135);
            this.txtaddress1.MaxLength = 32767;
            this.txtaddress1.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtaddress1.Modified = false;
            this.txtaddress1.Multiline = false;
            this.txtaddress1.Name = "txtaddress1";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtaddress1.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.Empty;
            stateProperties34.FillColor = System.Drawing.Color.White;
            stateProperties34.ForeColor = System.Drawing.Color.Empty;
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtaddress1.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtaddress1.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtaddress1.OnIdleState = stateProperties36;
            this.txtaddress1.PasswordChar = '\0';
            this.txtaddress1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtaddress1.PlaceholderText = "";
            this.txtaddress1.ReadOnly = false;
            this.txtaddress1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtaddress1.SelectedText = "";
            this.txtaddress1.SelectionLength = 0;
            this.txtaddress1.SelectionStart = 0;
            this.txtaddress1.ShortcutsEnabled = true;
            this.txtaddress1.Size = new System.Drawing.Size(391, 25);
            this.txtaddress1.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtaddress1.TabIndex = 116;
            this.txtaddress1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtaddress1.TextMarginBottom = 0;
            this.txtaddress1.TextMarginLeft = 5;
            this.txtaddress1.TextMarginTop = 0;
            this.txtaddress1.TextPlaceholder = "";
            this.txtaddress1.UseSystemPasswordChar = false;
            this.txtaddress1.WordWrap = true;
            this.txtaddress1.KeyDown += new System.Windows.Forms.KeyEventHandler(this.Txtaddress1_KeyDown);
            // 
            // lbladdress1
            // 
            appearance12.BorderColor = System.Drawing.Color.White;
            appearance12.ForeColor = System.Drawing.Color.White;
            this.lbladdress1.Appearance = appearance12;
            this.lbladdress1.Font = new System.Drawing.Font("Arial", 8.25F, System.Drawing.FontStyle.Bold);
            this.lbladdress1.Location = new System.Drawing.Point(26, 138);
            this.lbladdress1.Name = "lbladdress1";
            this.lbladdress1.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.lbladdress1.Size = new System.Drawing.Size(79, 19);
            this.lbladdress1.TabIndex = 117;
            this.lbladdress1.Text = ": Address 1";
            // 
            // lbladdress2
            // 
            appearance11.BorderColor = System.Drawing.Color.White;
            appearance11.ForeColor = System.Drawing.Color.White;
            this.lbladdress2.Appearance = appearance11;
            this.lbladdress2.Font = new System.Drawing.Font("Arial", 8.25F, System.Drawing.FontStyle.Bold);
            this.lbladdress2.Location = new System.Drawing.Point(26, 171);
            this.lbladdress2.Name = "lbladdress2";
            this.lbladdress2.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.lbladdress2.Size = new System.Drawing.Size(79, 19);
            this.lbladdress2.TabIndex = 119;
            this.lbladdress2.Text = ": Address 2";
            // 
            // txtaddress2
            // 
            this.txtaddress2.AcceptsReturn = false;
            this.txtaddress2.AcceptsTab = false;
            this.txtaddress2.AnimationSpeed = 200;
            this.txtaddress2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtaddress2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtaddress2.BackColor = System.Drawing.Color.Transparent;
            this.txtaddress2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtaddress2.BackgroundImage")));
            this.txtaddress2.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtaddress2.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtaddress2.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtaddress2.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtaddress2.BorderRadius = 10;
            this.txtaddress2.BorderThickness = 1;
            this.txtaddress2.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
            this.txtaddress2.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtaddress2.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtaddress2.DefaultText = "";
            this.txtaddress2.FillColor = System.Drawing.Color.White;
            this.txtaddress2.HideSelection = true;
            this.txtaddress2.IconLeft = null;
            this.txtaddress2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtaddress2.IconPadding = 10;
            this.txtaddress2.IconRight = null;
            this.txtaddress2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtaddress2.Lines = new string[0];
            this.txtaddress2.Location = new System.Drawing.Point(110, 168);
            this.txtaddress2.MaxLength = 32767;
            this.txtaddress2.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtaddress2.Modified = false;
            this.txtaddress2.Multiline = false;
            this.txtaddress2.Name = "txtaddress2";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtaddress2.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.Empty;
            stateProperties30.FillColor = System.Drawing.Color.White;
            stateProperties30.ForeColor = System.Drawing.Color.Empty;
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtaddress2.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtaddress2.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtaddress2.OnIdleState = stateProperties32;
            this.txtaddress2.PasswordChar = '\0';
            this.txtaddress2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtaddress2.PlaceholderText = "";
            this.txtaddress2.ReadOnly = false;
            this.txtaddress2.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtaddress2.SelectedText = "";
            this.txtaddress2.SelectionLength = 0;
            this.txtaddress2.SelectionStart = 0;
            this.txtaddress2.ShortcutsEnabled = true;
            this.txtaddress2.Size = new System.Drawing.Size(391, 25);
            this.txtaddress2.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtaddress2.TabIndex = 118;
            this.txtaddress2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtaddress2.TextMarginBottom = 0;
            this.txtaddress2.TextMarginLeft = 5;
            this.txtaddress2.TextMarginTop = 0;
            this.txtaddress2.TextPlaceholder = "";
            this.txtaddress2.UseSystemPasswordChar = false;
            this.txtaddress2.WordWrap = true;
            this.txtaddress2.KeyDown += new System.Windows.Forms.KeyEventHandler(this.Txtaddress2_KeyDown);
            // 
            // lblphone1
            // 
            appearance10.BorderColor = System.Drawing.Color.White;
            appearance10.ForeColor = System.Drawing.Color.White;
            this.lblphone1.Appearance = appearance10;
            this.lblphone1.Font = new System.Drawing.Font("Arial", 8.25F, System.Drawing.FontStyle.Bold);
            this.lblphone1.Location = new System.Drawing.Point(26, 204);
            this.lblphone1.Name = "lblphone1";
            this.lblphone1.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.lblphone1.Size = new System.Drawing.Size(79, 19);
            this.lblphone1.TabIndex = 121;
            this.lblphone1.Text = ": Phone ";
            // 
            // txtphone1
            // 
            this.txtphone1.AcceptsReturn = false;
            this.txtphone1.AcceptsTab = false;
            this.txtphone1.AnimationSpeed = 200;
            this.txtphone1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtphone1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtphone1.BackColor = System.Drawing.Color.Transparent;
            this.txtphone1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtphone1.BackgroundImage")));
            this.txtphone1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtphone1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtphone1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtphone1.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtphone1.BorderRadius = 10;
            this.txtphone1.BorderThickness = 1;
            this.txtphone1.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
            this.txtphone1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtphone1.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtphone1.DefaultText = "";
            this.txtphone1.FillColor = System.Drawing.Color.White;
            this.txtphone1.HideSelection = true;
            this.txtphone1.IconLeft = null;
            this.txtphone1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtphone1.IconPadding = 10;
            this.txtphone1.IconRight = null;
            this.txtphone1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtphone1.Lines = new string[0];
            this.txtphone1.Location = new System.Drawing.Point(111, 201);
            this.txtphone1.MaxLength = 32767;
            this.txtphone1.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtphone1.Modified = false;
            this.txtphone1.Multiline = false;
            this.txtphone1.Name = "txtphone1";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtphone1.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.Empty;
            stateProperties26.FillColor = System.Drawing.Color.White;
            stateProperties26.ForeColor = System.Drawing.Color.Empty;
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtphone1.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtphone1.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtphone1.OnIdleState = stateProperties28;
            this.txtphone1.PasswordChar = '\0';
            this.txtphone1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtphone1.PlaceholderText = "";
            this.txtphone1.ReadOnly = false;
            this.txtphone1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtphone1.SelectedText = "";
            this.txtphone1.SelectionLength = 0;
            this.txtphone1.SelectionStart = 0;
            this.txtphone1.ShortcutsEnabled = true;
            this.txtphone1.Size = new System.Drawing.Size(163, 25);
            this.txtphone1.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtphone1.TabIndex = 120;
            this.txtphone1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtphone1.TextMarginBottom = 0;
            this.txtphone1.TextMarginLeft = 5;
            this.txtphone1.TextMarginTop = 0;
            this.txtphone1.TextPlaceholder = "";
            this.txtphone1.UseSystemPasswordChar = false;
            this.txtphone1.WordWrap = true;
            this.txtphone1.KeyDown += new System.Windows.Forms.KeyEventHandler(this.Txtphone1_KeyDown);
            // 
            // lblemail
            // 
            appearance9.BorderColor = System.Drawing.Color.White;
            appearance9.ForeColor = System.Drawing.Color.White;
            this.lblemail.Appearance = appearance9;
            this.lblemail.Font = new System.Drawing.Font("Arial", 8.25F, System.Drawing.FontStyle.Bold);
            this.lblemail.Location = new System.Drawing.Point(2, 267);
            this.lblemail.Name = "lblemail";
            this.lblemail.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.lblemail.Size = new System.Drawing.Size(103, 19);
            this.lblemail.TabIndex = 125;
            this.lblemail.Text = ": Email";
            // 
            // txtemail
            // 
            this.txtemail.AcceptsReturn = false;
            this.txtemail.AcceptsTab = false;
            this.txtemail.AnimationSpeed = 200;
            this.txtemail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtemail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtemail.BackColor = System.Drawing.Color.Transparent;
            this.txtemail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtemail.BackgroundImage")));
            this.txtemail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtemail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtemail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtemail.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtemail.BorderRadius = 10;
            this.txtemail.BorderThickness = 1;
            this.txtemail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtemail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtemail.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtemail.DefaultText = "";
            this.txtemail.FillColor = System.Drawing.Color.White;
            this.txtemail.HideSelection = true;
            this.txtemail.IconLeft = null;
            this.txtemail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtemail.IconPadding = 10;
            this.txtemail.IconRight = null;
            this.txtemail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtemail.Lines = new string[0];
            this.txtemail.Location = new System.Drawing.Point(110, 264);
            this.txtemail.MaxLength = 32767;
            this.txtemail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtemail.Modified = false;
            this.txtemail.Multiline = false;
            this.txtemail.Name = "txtemail";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtemail.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.Empty;
            stateProperties22.FillColor = System.Drawing.Color.White;
            stateProperties22.ForeColor = System.Drawing.Color.Empty;
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtemail.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtemail.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtemail.OnIdleState = stateProperties24;
            this.txtemail.PasswordChar = '\0';
            this.txtemail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtemail.PlaceholderText = "";
            this.txtemail.ReadOnly = false;
            this.txtemail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtemail.SelectedText = "";
            this.txtemail.SelectionLength = 0;
            this.txtemail.SelectionStart = 0;
            this.txtemail.ShortcutsEnabled = true;
            this.txtemail.Size = new System.Drawing.Size(391, 25);
            this.txtemail.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtemail.TabIndex = 124;
            this.txtemail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtemail.TextMarginBottom = 0;
            this.txtemail.TextMarginLeft = 5;
            this.txtemail.TextMarginTop = 0;
            this.txtemail.TextPlaceholder = "";
            this.txtemail.UseSystemPasswordChar = false;
            this.txtemail.WordWrap = true;
            this.txtemail.KeyDown += new System.Windows.Forms.KeyEventHandler(this.Txtemail_KeyDown);
            // 
            // lblwebsite
            // 
            appearance7.BorderColor = System.Drawing.Color.White;
            appearance7.ForeColor = System.Drawing.Color.White;
            this.lblwebsite.Appearance = appearance7;
            this.lblwebsite.Font = new System.Drawing.Font("Arial", 8.25F, System.Drawing.FontStyle.Bold);
            this.lblwebsite.Location = new System.Drawing.Point(26, 299);
            this.lblwebsite.Name = "lblwebsite";
            this.lblwebsite.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.lblwebsite.Size = new System.Drawing.Size(79, 19);
            this.lblwebsite.TabIndex = 127;
            this.lblwebsite.Text = ": Website";
            // 
            // txtwebsite
            // 
            this.txtwebsite.AcceptsReturn = false;
            this.txtwebsite.AcceptsTab = false;
            this.txtwebsite.AnimationSpeed = 200;
            this.txtwebsite.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtwebsite.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtwebsite.BackColor = System.Drawing.Color.Transparent;
            this.txtwebsite.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtwebsite.BackgroundImage")));
            this.txtwebsite.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtwebsite.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtwebsite.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtwebsite.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtwebsite.BorderRadius = 10;
            this.txtwebsite.BorderThickness = 1;
            this.txtwebsite.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtwebsite.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtwebsite.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtwebsite.DefaultText = "";
            this.txtwebsite.FillColor = System.Drawing.Color.White;
            this.txtwebsite.HideSelection = true;
            this.txtwebsite.IconLeft = null;
            this.txtwebsite.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtwebsite.IconPadding = 10;
            this.txtwebsite.IconRight = null;
            this.txtwebsite.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtwebsite.Lines = new string[0];
            this.txtwebsite.Location = new System.Drawing.Point(109, 296);
            this.txtwebsite.MaxLength = 32767;
            this.txtwebsite.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtwebsite.Modified = false;
            this.txtwebsite.Multiline = false;
            this.txtwebsite.Name = "txtwebsite";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtwebsite.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Empty;
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.Empty;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtwebsite.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtwebsite.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtwebsite.OnIdleState = stateProperties16;
            this.txtwebsite.PasswordChar = '\0';
            this.txtwebsite.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtwebsite.PlaceholderText = "";
            this.txtwebsite.ReadOnly = false;
            this.txtwebsite.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtwebsite.SelectedText = "";
            this.txtwebsite.SelectionLength = 0;
            this.txtwebsite.SelectionStart = 0;
            this.txtwebsite.ShortcutsEnabled = true;
            this.txtwebsite.Size = new System.Drawing.Size(391, 25);
            this.txtwebsite.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtwebsite.TabIndex = 126;
            this.txtwebsite.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtwebsite.TextMarginBottom = 0;
            this.txtwebsite.TextMarginLeft = 5;
            this.txtwebsite.TextMarginTop = 0;
            this.txtwebsite.TextPlaceholder = "";
            this.txtwebsite.UseSystemPasswordChar = false;
            this.txtwebsite.WordWrap = true;
            this.txtwebsite.KeyDown += new System.Windows.Forms.KeyEventHandler(this.Txtwebsite_KeyDown);
            // 
            // lbllicence
            // 
            appearance6.BorderColor = System.Drawing.Color.White;
            appearance6.ForeColor = System.Drawing.Color.White;
            this.lbllicence.Appearance = appearance6;
            this.lbllicence.Font = new System.Drawing.Font("Arial", 8.25F, System.Drawing.FontStyle.Bold);
            this.lbllicence.Location = new System.Drawing.Point(26, 332);
            this.lbllicence.Name = "lbllicence";
            this.lbllicence.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.lbllicence.Size = new System.Drawing.Size(79, 19);
            this.lbllicence.TabIndex = 129;
            this.lbllicence.Text = ": Licence";
            // 
            // txtlicence
            // 
            this.txtlicence.AcceptsReturn = false;
            this.txtlicence.AcceptsTab = false;
            this.txtlicence.AnimationSpeed = 200;
            this.txtlicence.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtlicence.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtlicence.BackColor = System.Drawing.Color.Transparent;
            this.txtlicence.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtlicence.BackgroundImage")));
            this.txtlicence.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtlicence.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtlicence.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtlicence.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtlicence.BorderRadius = 10;
            this.txtlicence.BorderThickness = 1;
            this.txtlicence.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
            this.txtlicence.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtlicence.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtlicence.DefaultText = "";
            this.txtlicence.FillColor = System.Drawing.Color.White;
            this.txtlicence.HideSelection = true;
            this.txtlicence.IconLeft = null;
            this.txtlicence.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtlicence.IconPadding = 10;
            this.txtlicence.IconRight = null;
            this.txtlicence.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtlicence.Lines = new string[0];
            this.txtlicence.Location = new System.Drawing.Point(110, 329);
            this.txtlicence.MaxLength = 32767;
            this.txtlicence.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtlicence.Modified = false;
            this.txtlicence.Multiline = false;
            this.txtlicence.Name = "txtlicence";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtlicence.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Empty;
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.Empty;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtlicence.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtlicence.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtlicence.OnIdleState = stateProperties12;
            this.txtlicence.PasswordChar = '\0';
            this.txtlicence.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtlicence.PlaceholderText = "";
            this.txtlicence.ReadOnly = false;
            this.txtlicence.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtlicence.SelectedText = "";
            this.txtlicence.SelectionLength = 0;
            this.txtlicence.SelectionStart = 0;
            this.txtlicence.ShortcutsEnabled = true;
            this.txtlicence.Size = new System.Drawing.Size(391, 25);
            this.txtlicence.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtlicence.TabIndex = 128;
            this.txtlicence.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtlicence.TextMarginBottom = 0;
            this.txtlicence.TextMarginLeft = 5;
            this.txtlicence.TextMarginTop = 0;
            this.txtlicence.TextPlaceholder = "";
            this.txtlicence.UseSystemPasswordChar = false;
            this.txtlicence.WordWrap = true;
            this.txtlicence.KeyDown += new System.Windows.Forms.KeyEventHandler(this.Txtlicence_KeyDown);
            // 
            // lblremarks
            // 
            appearance5.BorderColor = System.Drawing.Color.White;
            appearance5.ForeColor = System.Drawing.Color.White;
            this.lblremarks.Appearance = appearance5;
            this.lblremarks.Font = new System.Drawing.Font("Arial", 8.25F, System.Drawing.FontStyle.Bold);
            this.lblremarks.Location = new System.Drawing.Point(26, 362);
            this.lblremarks.Name = "lblremarks";
            this.lblremarks.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.lblremarks.Size = new System.Drawing.Size(79, 19);
            this.lblremarks.TabIndex = 131;
            this.lblremarks.Text = ": Remark";
            // 
            // txtremark
            // 
            this.txtremark.AcceptsReturn = false;
            this.txtremark.AcceptsTab = false;
            this.txtremark.AnimationSpeed = 200;
            this.txtremark.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtremark.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtremark.BackColor = System.Drawing.Color.Transparent;
            this.txtremark.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtremark.BackgroundImage")));
            this.txtremark.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtremark.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtremark.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtremark.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtremark.BorderRadius = 10;
            this.txtremark.BorderThickness = 1;
            this.txtremark.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
            this.txtremark.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtremark.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtremark.DefaultText = "";
            this.txtremark.FillColor = System.Drawing.Color.White;
            this.txtremark.HideSelection = true;
            this.txtremark.IconLeft = null;
            this.txtremark.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtremark.IconPadding = 10;
            this.txtremark.IconRight = null;
            this.txtremark.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtremark.Lines = new string[0];
            this.txtremark.Location = new System.Drawing.Point(110, 362);
            this.txtremark.MaxLength = 32767;
            this.txtremark.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtremark.Modified = false;
            this.txtremark.Multiline = true;
            this.txtremark.Name = "txtremark";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtremark.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Empty;
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.Empty;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtremark.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtremark.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtremark.OnIdleState = stateProperties8;
            this.txtremark.PasswordChar = '\0';
            this.txtremark.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtremark.PlaceholderText = "";
            this.txtremark.ReadOnly = false;
            this.txtremark.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtremark.SelectedText = "";
            this.txtremark.SelectionLength = 0;
            this.txtremark.SelectionStart = 0;
            this.txtremark.ShortcutsEnabled = true;
            this.txtremark.Size = new System.Drawing.Size(391, 61);
            this.txtremark.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtremark.TabIndex = 130;
            this.txtremark.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtremark.TextMarginBottom = 0;
            this.txtremark.TextMarginLeft = 5;
            this.txtremark.TextMarginTop = 0;
            this.txtremark.TextPlaceholder = "";
            this.txtremark.UseSystemPasswordChar = false;
            this.txtremark.WordWrap = true;
            this.txtremark.KeyDown += new System.Windows.Forms.KeyEventHandler(this.Txtremark_KeyDown);
            // 
            // lblphone2
            // 
            appearance4.BorderColor = System.Drawing.Color.White;
            appearance4.ForeColor = System.Drawing.Color.White;
            this.lblphone2.Appearance = appearance4;
            this.lblphone2.Font = new System.Drawing.Font("Arial", 8.25F, System.Drawing.FontStyle.Bold);
            this.lblphone2.Location = new System.Drawing.Point(274, 204);
            this.lblphone2.Name = "lblphone2";
            this.lblphone2.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.lblphone2.Size = new System.Drawing.Size(66, 19);
            this.lblphone2.TabIndex = 133;
            this.lblphone2.Text = ": Phone ";
            // 
            // txtphon2
            // 
            this.txtphon2.AcceptsReturn = false;
            this.txtphon2.AcceptsTab = false;
            this.txtphon2.AnimationSpeed = 200;
            this.txtphon2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtphon2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtphon2.BackColor = System.Drawing.Color.Transparent;
            this.txtphon2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtphon2.BackgroundImage")));
            this.txtphon2.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtphon2.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtphon2.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtphon2.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtphon2.BorderRadius = 10;
            this.txtphon2.BorderThickness = 1;
            this.txtphon2.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
            this.txtphon2.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtphon2.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtphon2.DefaultText = "";
            this.txtphon2.FillColor = System.Drawing.Color.White;
            this.txtphon2.HideSelection = true;
            this.txtphon2.IconLeft = null;
            this.txtphon2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtphon2.IconPadding = 10;
            this.txtphon2.IconRight = null;
            this.txtphon2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtphon2.Lines = new string[0];
            this.txtphon2.Location = new System.Drawing.Point(338, 201);
            this.txtphon2.MaxLength = 32767;
            this.txtphon2.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtphon2.Modified = false;
            this.txtphon2.Multiline = false;
            this.txtphon2.Name = "txtphon2";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtphon2.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Empty;
            stateProperties2.FillColor = System.Drawing.Color.White;
            stateProperties2.ForeColor = System.Drawing.Color.Empty;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtphon2.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtphon2.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtphon2.OnIdleState = stateProperties4;
            this.txtphon2.PasswordChar = '\0';
            this.txtphon2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtphon2.PlaceholderText = "";
            this.txtphon2.ReadOnly = false;
            this.txtphon2.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtphon2.SelectedText = "";
            this.txtphon2.SelectionLength = 0;
            this.txtphon2.SelectionStart = 0;
            this.txtphon2.ShortcutsEnabled = true;
            this.txtphon2.Size = new System.Drawing.Size(163, 25);
            this.txtphon2.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtphon2.TabIndex = 132;
            this.txtphon2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtphon2.TextMarginBottom = 0;
            this.txtphon2.TextMarginLeft = 5;
            this.txtphon2.TextMarginTop = 0;
            this.txtphon2.TextPlaceholder = "";
            this.txtphon2.UseSystemPasswordChar = false;
            this.txtphon2.WordWrap = true;
            this.txtphon2.KeyDown += new System.Windows.Forms.KeyEventHandler(this.Txtphon2_KeyDown);
            // 
            // txtfax
            // 
            this.txtfax.AcceptsReturn = false;
            this.txtfax.AcceptsTab = false;
            this.txtfax.AnimationSpeed = 200;
            this.txtfax.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtfax.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtfax.BackColor = System.Drawing.Color.Transparent;
            this.txtfax.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtfax.BackgroundImage")));
            this.txtfax.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtfax.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtfax.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtfax.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtfax.BorderRadius = 10;
            this.txtfax.BorderThickness = 1;
            this.txtfax.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
            this.txtfax.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtfax.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtfax.DefaultText = "";
            this.txtfax.FillColor = System.Drawing.Color.White;
            this.txtfax.HideSelection = true;
            this.txtfax.IconLeft = null;
            this.txtfax.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtfax.IconPadding = 10;
            this.txtfax.IconRight = null;
            this.txtfax.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtfax.Lines = new string[0];
            this.txtfax.Location = new System.Drawing.Point(111, 232);
            this.txtfax.MaxLength = 32767;
            this.txtfax.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtfax.Modified = false;
            this.txtfax.Multiline = false;
            this.txtfax.Name = "txtfax";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtfax.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Empty;
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.Empty;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtfax.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtfax.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtfax.OnIdleState = stateProperties20;
            this.txtfax.PasswordChar = '\0';
            this.txtfax.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtfax.PlaceholderText = "";
            this.txtfax.ReadOnly = false;
            this.txtfax.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtfax.SelectedText = "";
            this.txtfax.SelectionLength = 0;
            this.txtfax.SelectionStart = 0;
            this.txtfax.ShortcutsEnabled = true;
            this.txtfax.Size = new System.Drawing.Size(391, 25);
            this.txtfax.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txtfax.TabIndex = 124;
            this.txtfax.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtfax.TextMarginBottom = 0;
            this.txtfax.TextMarginLeft = 5;
            this.txtfax.TextMarginTop = 0;
            this.txtfax.TextPlaceholder = "";
            this.txtfax.UseSystemPasswordChar = false;
            this.txtfax.WordWrap = true;
            this.txtfax.KeyDown += new System.Windows.Forms.KeyEventHandler(this.Txtfax_KeyDown);
            // 
            // lblfax
            // 
            appearance8.BorderColor = System.Drawing.Color.White;
            appearance8.ForeColor = System.Drawing.Color.White;
            this.lblfax.Appearance = appearance8;
            this.lblfax.Font = new System.Drawing.Font("Arial", 8.25F, System.Drawing.FontStyle.Bold);
            this.lblfax.Location = new System.Drawing.Point(26, 235);
            this.lblfax.Name = "lblfax";
            this.lblfax.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.lblfax.Size = new System.Drawing.Size(79, 19);
            this.lblfax.TabIndex = 125;
            this.lblfax.Text = ": Fax";
            // 
            // SupplierMaster
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(64)))), ((int)(((byte)(89)))));
            this.ClientSize = new System.Drawing.Size(556, 490);
            this.Controls.Add(this.lblphone2);
            this.Controls.Add(this.txtphon2);
            this.Controls.Add(this.lblremarks);
            this.Controls.Add(this.txtremark);
            this.Controls.Add(this.lbllicence);
            this.Controls.Add(this.txtlicence);
            this.Controls.Add(this.lblwebsite);
            this.Controls.Add(this.txtwebsite);
            this.Controls.Add(this.lblfax);
            this.Controls.Add(this.lblemail);
            this.Controls.Add(this.txtfax);
            this.Controls.Add(this.txtemail);
            this.Controls.Add(this.lblphone1);
            this.Controls.Add(this.txtphone1);
            this.Controls.Add(this.lbladdress2);
            this.Controls.Add(this.txtaddress2);
            this.Controls.Add(this.lbladdress1);
            this.Controls.Add(this.txtaddress1);
            this.Controls.Add(this.chkblock);
            this.Controls.Add(this.btnClose);
            this.Controls.Add(this.btnDelete);
            this.Controls.Add(this.btnSave);
            this.Controls.Add(this.txtusername);
            this.Controls.Add(this.txtname);
            this.Controls.Add(this.txtcode);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.lbltitle);
            this.Controls.Add(this.lblcode);
            this.Controls.Add(this.lblname);
            this.Controls.Add(this.lbluser);
            this.Controls.Add(this.lblstatus);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "SupplierMaster";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "ItemMaster2";
            this.Load += new System.EventHandler(this.ItemMaster2_Load);
            ((System.ComponentModel.ISupportInitialize)(this.btnClose)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Infragistics.Win.Misc.UltraLabel lbluser;
        private Infragistics.Win.Misc.UltraLabel lblname;
        private Infragistics.Win.Misc.UltraLabel lblcode;
        private System.Windows.Forms.Label lbltitle;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel panel2;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtcode;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtname;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtusername;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSave;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDelete;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.Framework.UI.BunifuImageButton btnClose;
        private Bunifu.Framework.UI.BunifuCheckbox chkblock;
        private Infragistics.Win.Misc.UltraLabel lblstatus;
        private Infragistics.Win.Misc.UltraLabel lblphone1;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtphone1;
        private Infragistics.Win.Misc.UltraLabel lbladdress2;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtaddress2;
        private Infragistics.Win.Misc.UltraLabel lbladdress1;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtaddress1;
        private Infragistics.Win.Misc.UltraLabel lblremarks;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtremark;
        private Infragistics.Win.Misc.UltraLabel lbllicence;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtlicence;
        private Infragistics.Win.Misc.UltraLabel lblwebsite;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtwebsite;
        private Infragistics.Win.Misc.UltraLabel lblemail;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtemail;
        private Infragistics.Win.Misc.UltraLabel lblphone2;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtphon2;
        private Infragistics.Win.Misc.UltraLabel lblfax;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtfax;
    }
}